## Implementation of Camera Calibration through OpenCV

In [3]:
# Imports
import cv2
import numpy as np
# import os 
import glob

## Define dimensions of checkerboard

In [4]:
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

## Define world coordinates for 3D points

In [5]:
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

## Extract path of individual image stored in ChessBoards folder

In [6]:
# Need to calibrate with more than one image ideally. 
images = glob.glob('./Images/ChessBoards/*.jpg') 
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 

## Camera calibration using OpenCV
* Zhang based calibration


In [7]:
"""
Performing camera calibration by passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the detected corners (imgpoints)
"""

ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)


print("Camera matrix : \n")
print(mtx)
print("\n dist : \n")
print(dist)
print("\n rvecs : \n")
print(rvecs)
print("\n tvecs : \n")
print(tvecs)

Camera matrix : 

[[306.90932227   0.         232.73436779]
 [  0.         329.49901714 237.4364363 ]
 [  0.           0.           1.        ]]

 dist : 

[[-0.08150661 -0.33226508 -0.02329393  0.01211733  1.31739346]]

 rvecs : 

(array([[-0.35227402],
       [ 0.03503426],
       [-0.00956213]]),)

 tvecs : 

(array([[-2.73252029],
       [-6.45052168],
       [11.85588828]]),)
